package com.app.enums;

public enum Specialization {
    CROP_SCIENCE,
    SOIL_SCIENCE,
    PLANT_PATHOLOGY,
    AGRICULTURAL_ENTOMOLOGY,
    AGRICULTURAL_ECONOMICS,
    HORTICULTURE,
    IRRIGATION_ENGINEERING,
    AGRONOMY,
    AGRICULTURAL_ENGINEERING,
    PEST_MANAGEMENT
}

